### ISSUE TITLE
According htop 977M, but 1024 has been defined

### ISSUE THREAD

**Issue by 030** [kamaln7/ansible-swapfile#11]
```
swapfile_size: 1024MB
```

**Comment by damoon** [comment]
i can reproduce this.
you need to write 1024MiB instead of 1024MB.

**Comment by kamaln7** [comment]
This seems to be simply a matter of using the right units. Correct me if I'm wrong, of course, but I'm closing this for now :)

**Comment by 030** [comment]
the MiB works
