### ISSUE TITLE
Does somebody maintain this repo?

### ISSUE THREAD

**Issue by 030** [kamaln7/ansible-swapfile#26]

**Comment by kamaln7** [comment]
Not really 😞 Unfortunately I did not have enough time to dedicate to this repo as I had stopped using Ansible and it would've required me to keep up with all the changes + test every commit. I'd suggest using one of the forks: [full list](https://github.com/kamaln7/ansible-swapfile/network). [This one](https://github.com/Oefenweb/ansible-swapfile) in particular was the very first fork and seems well-maintained.

**Comment by 030** [comment]
Thank you for explaining. Could you clarify this in the Readme. This will ensure that people create the issue in the right repo, e.g. DEPRATED - use https://github.com/Oefenweb/ansible-swapfile instead
